<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>
    
    <?php if($_SESSION['authorized']): ?>
        <a href="balans">Change Balans</a>
        <a href="map">Map</a>
        <a href="logout">Logout</a>
    <?php else: ?>
        <a href="login">Login</a>
        <a href="registration">Registration</a>
        <a href="balans">Change Balans</a>
        <a href="map">Map</a>
    <?php endif; ?>

</body>
</html>