<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Map</title>
</head>
<body>

    <h1>Get Distance</h1>
    <form action="getDistance" method="POST">
        <input type="text" name="from" placeholder="From">
        <input type="text" name="to" placeholder="To">
        <input type="submit">
    </form>
    
</body>
</html>