<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration</title>
</head>
<body>

    <h1>Registration</h1>

    <form action="registration" method="POST">
        <input type="text" name="login" placeholder="Login" required>
        <input type="password" name="pass" placeholder="Password" required>
        <input type="submit" value="Registration">
    </form>
    
</body>
</html>